apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-actions-app
  labels:
    app: hello-actions-app
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-actions-app
  template:
    metadata:
      labels:
        app: hello-actions-app
    spec:
      containers:
      - name: hello-actions-app
        image: gcr.io/agile-terra-275621/hello-app-actions
        ports:
        - containerPort: 8080